name: Generate docs

on:
  push:
    branches:
      - trunk
    paths:
      - 'features/src/**/devcontainer-feature.json'
      - 'features/src/**/NOTES.md'
      - '.github/workflows/generate-docs.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-feature-docs:
    name: Generate documentation for features
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
  
      - name: Generate documentation
        uses: devcontainers/action@528049dce833673f136ddfc09c2720d450029a6b # v1.4.2
        with:
          generate-docs: true
          base-path-to-features: ./features/src

      - name: Create a PR for documentation
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7.0.1
        with:
          add-paths: ':(glob)features/src/**/README.md'
          commit-message: 'docs: automated documentation update'
          title: 'docs: automated documentation update'
          body: 'Update documentation for features'
          labels: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
