name: ShellCheck

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint with shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Run shellcheck
        run: shellcheck -o all -f gcc $(find . -path ./.git -prune -o -type f -executable -print)
