name: ShellCheck

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint with shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Run shellcheck
        run: shellcheck -o all -s sh -f gcc $(find . -path ./.git -prune -o -type f -executable -print)
