name: ShellCheck

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint with shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/problem-matcher-gcc.json"

      - name: Run shellcheck
        run: shellcheck -o all -f gcc $(find . -path ./.git -prune -o -type f -executable -print)
