name: Validate Features

on:
  pull_request:
    paths:
      - "features/src/**/devcontainer-feature.json"
      - ".github/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: Validate devcontainer-feature.json files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@528049dce833673f136ddfc09c2720d450029a6b # v1.4.2
        with:
          validate-only: "true"
          base-path-to-features: "./features/src"
